pipeline:

  pypi-publish:
    image: gjtempleton/drone-pypi
    when:
      event: tag
    secrets: [ pypi_username, pypi_password ]
    repository: https://upload.pypi.org/legacy/
    username: ${PYPI_USERNAME}
    password: ${PYPI_PASSWORD}
