pipeline:

  pypi-publish:
    image: python:3.6-slim
    when:
      event: tag
    secrets: [ pypi_username, pypi_password ]
    commands:
      - pip install twine
      - python setup.py sdist bdist_wheel
      - twine upload -u $${PYPI_USERNAME} -p $${PYPI_PASSWORD} dist/*

